### ISSUE TITLE
rake turkee:post_hit: wrong number of arguments (6 for 7) 

### ISSUE THREAD

**Issue by nmaisonneuve** [aantix/turkee#1]
Hi 
rake turkee:post_hit ["Please complete our survey", "Tell us your favorite color.", "Survey", 100, 0.05, 2]

(to fix also:  turkee:post_hit and not turkee:posthit in the README) 
==> 
wrong number of arguments (6 for 7)
c:/Ruby187/lib/ruby/gems/1.8/gems/turkee-1.0.2/lib/tasks/turkee.rb:11:in `create
_hit'
c:/Ruby187/lib/ruby/gems/1.8/gems/turkee-1.0.2/lib/tasks/turkee.rb:11
c:/Ruby187/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'

**Comment by aantix** [comment]
I have committed several fixes.  Can you install v1.0.3 and verify?  Thanks!
