### ISSUE TITLE
update tag

### ISSUE THREAD

**Issue by rajagopals** [aantix/turkee#11]
Hi,

Could you please update the latest release to the master. I was stumped for a while when Rails kept giving me 'can't mass-assign protected attributes' error.

Thanks!

**Comment by aantix** [comment]
Good thinking. I will try to get that done in the next couple of days.

**Comment by aantix** [comment]
1.2.0 has been released.

**Comment by rajagopals** [comment]
thanks!  Also, I noticed a possible error in the readme.

<% turkee_form_for(@survey, params) do |f| %> should be

<%= turkee_form_for(@survey, params) do |f| %> intead, right?

On Wed, May 9, 2012 at 11:01 PM, Jim Jones
reply@reply.github.com
wrote:

**Comment by aantix** [comment]
Ah, yes, you are correct.  I will update now.  Thanks!
