### ISSUE TITLE
undefined method `reverse_merge!' for nil:NilClass

### ISSUE THREAD

**Issue by workmaster2n** [aantix/turkee#12]
I'm trying to test out turkee but get a 'undefined method `reverse_merge!' for nil:NilClass' error when I try to view my form.

Here's the code:

```
class MechanicalTurksController < ApplicationController
  def new
    @mechanical_turk = MechanicalTurk.new
    @disabled = Turkee::TurkeeFormHelper::disable_form_fields?(params)
  end
end

<%= turkee_form_for(@mechanical_turk, params) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, disabled: @disabled %>

    <br />
    <%= f.submit "Save", class:"btn btn-primary", disabled: @disabled %>
<% end %>

class MechanicalTurk < ActiveRecord::Base

end
```

I've tried this on my development as well as staging servers, and get the same errors in both places.

The error comes from the `form_for_options` and it appears `params` is missing something?

The only parameters being passed to the call to `mecahnical_turks/new` are the `asignmentId` and `hitId`

**Comment by aantix** [comment]
I'll take a look tonight when I get home.  Thanks!

**Comment by aantix** [comment]
I'm running Rails 3.2 and not experiencing this. A couple of things.

1) Can you update your Gemfile to utilize the most recent build? Do you still receive the error?

gem 'turkee', :git => "https://github.com/aantix/turkee.git"

2) Can you send me the full stack trace?

**Comment by workmaster2n** [comment]
The most recent build worked for me.  I don't know if it was a bad download or not.  The previous version was 1.1.1 and now it is 1.1.1 from the provided url.  Getting an error on `turkee:get_all_results` now, but at least the form displays.  Thanks!
