### ISSUE TITLE
Turkee doesn't work with Rails 4

### ISSUE THREAD

**Issue by tomfakes** [aantix/turkee#17]
Trying to integrate Turkee into a new Rails 4 app I'm building, and the first thing that breaks is the usage of attr_accessible instead of strong parameters

Using the 'protected_attributes' gem gets me past this first problem.  I'll add more if I run into further issues

**Comment by aantix** [comment]
Thanks Tom. Haven't had any client or personal projects for Rails 4 yet, so I haven't looked at doing the migration.  I'd definitely accept that pull request if you're up for it. :)

**Comment by aantix** [comment]
Since Mechanical Turk will look to show your external forms in an iFrame, for Rails 4, you're going to have to remove the default security headers that would prevent this: 

E.g.

```
config.action_dispatch.default_headers.clear
```

http://edgeguides.rubyonrails.org/security.html#default-headers

**Comment by aantix** [comment]
Rails 4 support was merged in with PR https://github.com/aantix/turkee/pull/19
