### ISSUE TITLE
Rails 4 generate turkee fails

### ISSUE THREAD

**Issue by cheolhom** [aantix/turkee#20]
run rails g turkee

/deprecated_mass_assignment_security.rb:14:in `attr_accessible':`attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params

**Comment by cheolhom** [comment]
Only now saw latest checkins - added to Gemfile

gem 'turkee', :git => 'https://github.com/aantix/turkee.git', branch: 'master'

resolved.

**Comment by aantix** [comment]
Just updated the README to let Rails 4 users know they should be using the master branch.  Thanks.
