### ISSUE TITLE
sandbox parameter dispersed?

### ISSUE THREAD

**Issue by nmaisonneuve** [aantix/turkee#3]
Hi, 

about the sandbox parameter 
- there is 2 variables synchronize Rturk and Turkee 

*\* in rails app /initializer/turkee.rb
sandbox=(Rails.env == 'production' ? false : true)
RTurk.setup(AWSACCESSKEYID, AWSACCESSKEY, :sandbox => sandbox)

*\* and in turkee gems/ turkee.rb  
self.create_hit(host, hit_title, hit_description, typ, num_assignments, reward, lifetime, keywords, task_duration)
... 
      TurkeeTask.create(:sandbox             => (Rails.env == 'production' ? false : true),

so I want to configure the sandbox parameter in something else that depending of the production or development mode , I need to change the both variable

is there a way to create only 1 variable in Turkee that initialize RTurk

Nicolas

**Comment by aantix** [comment]
You could pass in the value of RTurk.sandbox?

```
TurkeeTask.create(:sandbox             => RTurk.sandbox?,
```

I will make that change.  Thanks!

Jim

**Comment by nmaisonneuve** [comment]
Thanks Jim for the support !

**Comment by nmaisonneuve** [comment]
Thanks Jim for the support !
