### ISSUE TITLE
Turkers can't submit HIT form

### ISSUE THREAD

**Issue by owenstrevor** [aantix/turkee#34]
Using  turkee_form_for(@model, params) as in the instructions

Turkers get this error:

```
There was a problem submitting your results for this HIT.

This HIT is still assigned to you. To try this HIT again, click "HITs Assigned To You" in the navigation bar, then click "Continue work on this HIT" for the HIT. If this problem persists, you can contact the Requester for this HIT using the "Contact" link above.

To return this HIT and continue working on other HITs, click the "Return HIT" button.
```

Neither the assignmentId, hit_id, or worker_id, is present in the form when I test it with a live HIT. Why could this be?

**Comment by owenstrevor** [comment]
**Update:** This makes no sense. I passed the params on my local server and the form helper generated the correct hidden fields.

For some reason my rails app is acting as if the params are not being passed at all, even though I see them in the iframe code.

**Comment by aantix** [comment]
Is this in production or the turk sandbox?

**Comment by owenstrevor** [comment]
Production. I think it has something to do with the iframe in Mturk. If I just pass the params in the URL and view the page directly the correct hidden fields are created. Then again it could be something else.

**Comment by owenstrevor** [comment]
Got it working! The issue was that my form is two pages (multi-step form). When Turk loads the first page, the params are in the URL, but when I step through to the second page those params are lost. All I had to do was pass the params through and it worked.
