### ISSUE TITLE
Firefox 4 form submission problem?

### ISSUE THREAD

**Issue by aantix** [aantix/turkee#6]
This appears to be browser specific but maybe others can shed some light on the subject.

When I pull up my hit with Firefox 4 and submit it, I get the following error message from Mechanical Turk :

  "This HIT is still assigned to you. To try this HIT again, click "HITs Assigned To You" in the navigation bar, then click   "Continue work on this HIT" for the HIT. If this problem persists, you can contact the Requester for this HIT using the "Contact" link above."

To return this HIT and continue working on other HITs, click the "Return HIT" button."

I do _not_ receive this error if I use Safari or IE.  Can anyone else validate this?  Maybe there's some security differences in the way FF 4 handles cross domain form posts?  I am going to have to monitor with Firebug::Net to see what headers are being sent.

**Comment by dpsk** [comment]
i have the same error in all browsers, when im trying to submit turkee_form :| Do you have fresh app, as example, not rails 2?

**Comment by aantix** [comment]
Here is a sample Rails 3 app.  I've posted it to Dropbox for now, I will post it to Github later.
http://dl.dropbox.com/u/3902239/turkee_test_rails3.zip

I only experienced the above issue with Firefox; Internet Explorer didn't seem to have an issue.  So maybe it's an issue of cross domain form submission security?

**Comment by aantix** [comment]
@dpsk -

Did you ever find a resolution to this issue?

**Comment by lswanson** [comment]
I ran into this problem and it turned out that I had a bug where I was not passing params into the turkee_form_for method in my view. 

`<%= turkee_form_for @model_object, params, :url => {:action => "update"} do |f| %>`

Thought I'd post an update in case anyone else runs across this in the future.
