### ISSUE TITLE
turkee requires turkee (>= 0)

### ISSUE THREAD

**Issue by millisami** [aantix/turkee#8]
When installing it from rubygems `gem install turkee`, I get the following error:

```
gem install turkee
ERROR:  Error installing turkee:
    turkee requires turkee (>= 0)
```

Then I cloned it and tried to install using `rake install`, the same error.

Actually there is a line in `.gemspec` file that adds turkee itself as a dependency. That might be the problem or may be due to the gem version installed i.e. 1.6.2 in my system.

**Comment by aantix** [comment]
I've updated the gemspec, removed some unneeded dependencies and have pushed v1.1.1.  

Can you do an update and see if this resolves the issue for you?

**Comment by aantix** [comment]
And if you still are experiencing an issue, can you create a new rails app (using >= 3.0.7), add turkee to the gem file, do a bundle install and tell me if you still experience issues?

**Comment by reuableahcim** [comment]
I was having the same issue with a 3.0.9 rails app but did as you said, added turkee to the gem file, did a bundle install and the error message went away.

**Comment by aantix** [comment]
Thanks reuableahcim.  I'm going to close out this issue as I haven't heard of any more problems.
